artifacts:
  appDependencies: {}

dependencies:
  compile: [string-utils:jar]
  compile-tests: [compile, string-utils:resolve-deps]
  test: [compile-tests]
  jar: [compile]
  build: [jar, test]
  run: [compile]

targets:
  resolve-deps:
    tasks:
      - maven-dep:
          coordinates:
            - org.json:json:20230227
          into: $appDependencies

  compile:
    tasks:
      - javac:
          sources: src/main/java/com/example/app/Application.java
          destination: build/classes
          classpath:
            - $appDependencies
            - ../string-utils/build/libs/string-utils.jar
          sourceVersion: "11"
          targetVersion: "11"

  compile-tests:
    tasks:
      - javac:
          sources: src/test/java/com/example/app/ApplicationTest.java
          destination: build/test-classes
          classpath:
            - $junitClasspath
            - $appDependencies
            - ../string-utils/build/libs/string-utils.jar
            - build/classes
          sourceVersion: "11"
          targetVersion: "11"

  test:
    tasks:
      - junit:
          testClasses: build/test-classes
          classpath:
            - $junitClasspath
            - $appDependencies
            - ../string-utils/build/libs/string-utils.jar
            - build/classes
          reports: build/reports
          version: 5

  jar:
    tasks:
      - jar:
          from: build/classes
          to: build/libs/app.jar
          mainClass: com.example.app.Application

  build: {}

  run:
    tasks:
      - java:
          mainClass: com.example.app.Application
          classpath:
            - $appDependencies
            - ../string-utils/build/libs/string-utils.jar
            - build/classes

  clean:
    clean:
      - compile
      - compile-tests
      - test
      - jar
