jvm:
  layout: maven
  source: "11"
  target: "11"

libraries:
  appDependencies:
    - org.json:json:20230227

variants:
  main:
    deps: [$appDependencies, string-utils:jar]
  test:
    deps:
      - $junitClasspath
      - $appDependencies
      - string-utils:jar
      - main

dependencies:
  compile-tests: [compile, string-utils:resolve-junitClasspath]
  test: [compile-tests]
  jar: [compile]
  build: [jar, test]
  run: [compile]

clean: [compile, compile-tests, test, jar]

targets:
  compile:
    - javac: main

  compile-tests:
    - javac: test

  test:
    - junit:
        testClasses: test
        reports: build/reports
        version: 5

  jar:
    - jar:
        from: build/classes
        to: build/libs/app.jar
        mainClass: com.example.app.Application

  run:
    - java:
        mainClass: com.example.app.Application
        classpath:
          - $appDependencies
          - string-utils:jar
          - main
