dependencies:
  compile: [lib:jar]
  jar: [compile]
  run: [compile]

clean: [compile, jar]

targets:
  compile:
    - javac:
        sources: src/com/example/app/Main.java
        destination: build/classes
        classpath:
          - ../lib/build/string-utils.jar

  jar:
    - jar:
        from: build/classes
        to: build/demo-app.jar
        mainClass: com.example.app.Main

  run:
    - java:
        mainClass: com.example.app.Main
        classpath:
          - build/classes
          - ../lib/build/string-utils.jar
