dependencies:
  compile: [lib:jar]
  jar: [compile]
  run: [compile]

targets:
  compile:
    tasks:
      - javac:
          sources: src/com/example/app/Main.java
          destination: build/classes
          classpath:
            - ../lib/build/string-utils.jar

  jar:
    tasks:
      - jar:
          from: build/classes
          to: build/demo-app.jar
          mainClass: com.example.app.Main

  run:
    tasks:
      - java:
          mainClass: com.example.app.Main
          classpath:
            - build/classes
            - ../lib/build/string-utils.jar

  clean:
    clean:
      - compile
      - jar
