artifacts:
  junitClasspath: {}

java:
  source: "11"
  target: "11"

dependencies:
  compile-tests: [compile]
  test: [compile-tests]
  jar: [compile]
  build: [jar, test]

clean: [compile, compile-tests, test, jar]

targets:
  resolve-deps:
    - maven-dep:
        preset: junit5
        into: $junitClasspath

  compile:
    - javac:
        sources: src/main/java/com/example/utils/StringUtils.java
        destination: build/classes

  compile-tests:
    - javac:
        sources: src/test/java/com/example/utils/StringUtilsTest.java
        destination: build/test-classes
        classpath:
          - $junitClasspath
          - build/classes

  test:
    - junit:
        testClasses: build/test-classes
        classpath:
          - $junitClasspath
          - build/classes
        reports: build/reports
        version: 5

  jar:
    - jar:
        from: build/classes
        to: build/libs/string-utils.jar
